# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  sql0l:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - "sqldata:/var/lib/mysql"

  wp01:
    depends_on:
      - sql0l
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
    volumes:
      - wordpresdata:/var/www/html
    ports:
      - "80:80"
  

volumes:
  sqldata:
  wordpresdata:




#docker container run --name sql01 -v sqldata:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=secret -d mariadb
#docker container run --name wp01 --link sql01:mysql -p 80:80 -d wordpress